# Generated by Django 2.1.2 on 2020-02-27 15:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComunaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ConstantNumeric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactInfoTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('TableID', models.UUIDField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('Message', models.CharField(max_length=140)),
                ('RedirectRouteID', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=60)),
                ('TableName', models.CharField(max_length=20)),
                ('RedirectRouteName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProvinciaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='RegionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_provincia', to='common.Region'),
        ),
        migrations.AddField(
            model_name='notification',
            name='NotificationTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_type', to='common.NotificationType'),
        ),
        migrations.AddField(
            model_name='notification',
            name='UserID',
            field=models.ManyToManyField(related_name='user_notification', to='users.User'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='ProvinciaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_comuna', to='common.Provincia'),
        ),
    ]
