# docker-compose.prod.yml

version: "3.7"

services:
  nginx:
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf:readonly
  
  ssilva-frontend:
    build:
      context: ./original-frontend
      dockerfile: Dockerfile.prod
    volumes:
      - type: bind
        source: ./original-frontend
        target: /app:readonly
  
  ssilva-backend:
    build:
      context: ./original-backend
      dockerfile: Dockerfile.prod
    volumes:
      - type: bind
        source: ./original-backend
        target: /app:readonly