# Generated by Django 4.0.2 on 2022-03-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_notificationtype_name'),
        ('ventas', '0002_usersummary_remove_promesa_datepayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='RegionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_cliente', to='common.region'),
        ),
    ]
