# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          name: Deploy to test server
          deployment: production
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get -y install rsync
            - npm install
            - npm run build
            - rsync -azvqn --delete build/ anhht83@35.220.230.239:/var/www/html/ssilva-app
