# syntax=docker/dockerfile:1

FROM node:10.24.1

RUN mkdir /app

WORKDIR /app

ENV NODE_ENV=production
ENV API_ROOT=http://localhost/api

COPY ./package.json .

RUN npm install 

COPY . .

CMD [ "npm", "run", "start" ]