# Generated by Django 2.1.2 on 2020-02-27 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
                ('PermissionID', models.ManyToManyField(related_name='permission_role', to='users.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(blank=True, max_length=40, null=True)),
                ('LastNames', models.CharField(blank=True, max_length=60, null=True)),
                ('Rut', models.CharField(blank=True, error_messages={'unique': 'Rut ingresado ya existe en el sistema'}, max_length=12, null=True, unique=True)),
                ('Email', models.EmailField(blank=True, error_messages={'unique': 'Email ingresado ya existe en el sistema'}, max_length=60, null=True, unique=True)),
                ('DjangoUser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('RoleID', models.ManyToManyField(blank=True, related_name='role_user', to='users.Role')),
            ],
        ),
    ]
