# Generated by Django 2.1.2 on 2020-02-27 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import empresas_and_proyectos.models.project_documents
import empresas_and_proyectos.pdf_filename
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AseguradoraID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BorradorPromesaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorradorPromesaStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Constructora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ConstructoraID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('RazonSocial', models.CharField(max_length=150)),
                ('IsInmobiliaria', models.BooleanField(default=False)),
                ('IsConstructora', models.BooleanField(default=True)),
                ('State', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EdificioID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EtapaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
                ('SalesStartDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EtapaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EtapaStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='IngresoComisionesState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IngresoComisionesStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inmobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmobiliariaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Rut', models.CharField(max_length=12, unique=True)),
                ('RazonSocial', models.CharField(max_length=150, unique=True)),
                ('Direccion', models.CharField(max_length=150)),
                ('IsInmobiliaria', models.BooleanField(default=True)),
                ('IsConstructora', models.BooleanField(default=False)),
                ('State', models.BooleanField(default=True)),
                ('ComunaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_empresa', to='common.Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='InmobiliariaContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=60)),
                ('ContactInfoTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ContactInfoType')),
                ('InmobiliariaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmuebleID', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('Number', models.IntegerField()),
                ('Floor', models.IntegerField(blank=True, null=True)),
                ('BathroomQuantity', models.IntegerField(blank=True, null=True)),
                ('BedroomsQuantity', models.IntegerField(blank=True, null=True)),
                ('UtilSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TerraceSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('LodgeSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('TotalSquareMeters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('IsNotUsoyGoce', models.BooleanField(default=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MaximunDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('CotizacionDuration', models.IntegerField()),
                ('EdificioID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edificio_inmueble', to='empresas_and_proyectos.Edificio')),
                ('EtapaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_inmueble', to='empresas_and_proyectos.Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmuebleAID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_inmueble_a', to='empresas_and_proyectos.Inmueble')),
                ('InmuebleBID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_inmueble_b', to='empresas_and_proyectos.Inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleInmuebleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmuebleInmuebleTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmuebleStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmuebleTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionFinanciera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstitucionFinancieraID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrientationID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=10)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanMediosState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanMediosStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.models.project_documents.document_directory_path)),
                ('DocumentType', models.CharField(max_length=50)),
                ('State', models.CharField(choices=[('to_confirm', 'To Confirm'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='to_confirm', max_length=50)),
                ('ProjectID', models.CharField(max_length=100, null=True)),
                ('CreateAt', models.DateTimeField(default=datetime.datetime(2020, 2, 27, 15, 28, 16, 704310, tzinfo=utc))),
                ('NoExisted', models.BooleanField(default=False)),
                ('Poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_document', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=150)),
                ('Arquitecto', models.CharField(blank=True, max_length=150, null=True)),
                ('Symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=150, null=True)),
                ('CotizacionDuration', models.IntegerField(blank=True, null=True)),
                ('GuaranteeAmount', models.IntegerField(blank=True, null=True)),
                ('MoreThanOneEtapa', models.BooleanField(default=False)),
                ('EntregaInmediata', models.BooleanField(default=False)),
                ('BorradorPromesaState', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_borrador_promesa_proyecto', to='empresas_and_proyectos.BorradorPromesaState')),
                ('ComunaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuna_proyecto', to='common.Comuna')),
                ('ConstructoraID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constructora_proyecto', to='empresas_and_proyectos.Constructora')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoApprovalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoApprovalStateID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoAseguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoAseguradoraID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ExpirationDate', models.DateTimeField(blank=True, null=True)),
                ('AseguradoraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Aseguradora')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=60)),
                ('ContactInfoTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ContactInfoType')),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoLogID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Counter', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Comment', models.CharField(blank=True, max_length=150, null=True)),
                ('ProyectoDetailDocument', models.FileField(blank=True, null=True, upload_to=empresas_and_proyectos.pdf_filename.filename_proyecto_detail)),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoLogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoLogTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
                ('MaximunDays', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipologiaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInmobiliaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InmobiliariaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Inmobiliaria')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserInmobiliariaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserInmobiliariaTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProyectoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.Proyecto')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserProyectoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserProyectoTypeID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='userproyecto',
            name='UserProyectoTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.UserProyectoType'),
        ),
        migrations.AddField(
            model_name='userinmobiliaria',
            name='UserInmobiliariaTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.UserInmobiliariaType'),
        ),
        migrations.AddField(
            model_name='proyectolog',
            name='ProyectoLogTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_bitacora', to='empresas_and_proyectos.ProyectoLogType'),
        ),
        migrations.AddField(
            model_name='proyectolog',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContactInfo',
            field=models.ManyToManyField(related_name='contacto_proyecto', through='empresas_and_proyectos.ProyectoContactInfo', to='common.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Documents',
            field=models.ManyToManyField(related_name='document_project', to='empresas_and_proyectos.ProjectDocument'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='EtapaStateID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etapastate_proyecto', to='empresas_and_proyectos.EtapaState'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='IngresoComisionesState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_ingreso_comisiones_proyecto', to='empresas_and_proyectos.IngresoComisionesState'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='InmobiliariaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmobiliaria_proyecto', to='empresas_and_proyectos.Inmobiliaria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='InstitucionFinancieraID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion_financiera_proyecto', to='empresas_and_proyectos.InstitucionFinanciera'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='PlanMediosState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_plan_medios_proyecto', to='empresas_and_proyectos.PlanMediosState'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProyectoApprovalState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_aprobacion_proyecto', to='empresas_and_proyectos.ProyectoApprovalState'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProyectoAseguradoraID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aseguradora_proyecto', to='empresas_and_proyectos.ProyectoAseguradora'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProyectoLog',
            field=models.ManyToManyField(related_name='bitacora_proyecto', through='empresas_and_proyectos.ProyectoLog', to='users.User'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='UserProyecto',
            field=models.ManyToManyField(related_name='usuario_proyecto', through='empresas_and_proyectos.UserProyecto', to='users.User'),
        ),
        migrations.AddField(
            model_name='inmuebleinmueble',
            name='InmuebleInmuebleTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas_and_proyectos.InmuebleInmuebleType'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='InmuebleRestrict',
            field=models.ManyToManyField(through='empresas_and_proyectos.InmuebleInmueble', to='empresas_and_proyectos.Inmueble'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='InmuebleStateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_inmueble', to='empresas_and_proyectos.InmuebleState'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='InmuebleTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_inmueble', to='empresas_and_proyectos.InmuebleType'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='OrientationID',
            field=models.ManyToManyField(related_name='orientation_inmueble', to='empresas_and_proyectos.Orientation'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='TipologiaID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipologia_inmueble', to='empresas_and_proyectos.Tipologia'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='ContactInfo',
            field=models.ManyToManyField(related_name='contacto_empresa', through='empresas_and_proyectos.InmobiliariaContactInfo', to='common.ContactInfoType'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='UserInmobiliaria',
            field=models.ManyToManyField(related_name='user_inmobiliaria', through='empresas_and_proyectos.UserInmobiliaria', to='users.User'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='EtapaStateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_etapa', to='empresas_and_proyectos.EtapaState'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='ProyectoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_etapa', to='empresas_and_proyectos.Proyecto'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='EtapaID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapa_edificio', to='empresas_and_proyectos.Etapa'),
        ),
    ]
