# Generated by Django 4.0.2 on 2022-02-15 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='MaximunDiscount',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='BluePrint',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='MaximumDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='Up_Print',
            field=models.FileField(blank=True, null=True, upload_to='ProyectoDocuments/Inmueble'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ChileBankObservations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ChileBankReportDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ChileBankReportFile',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ChileBankState',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContadoAhorroPlus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContadoAhorroPlusMaxDiscounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContadoMontoCuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContadoMontoEscrituraContado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ContadoMontoPromesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditoAhorroPlus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditoAhorroPlusMaxDiscounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditoMontoCuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditoMontoEscrituraContado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='CreditoMontoPromesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='DeedStartDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='DeliverDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='DiscountMaxPercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='EscrituraProyectoState',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='IsSubsidy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MaxCuotas',
            field=models.IntegerField(blank=True, default=24, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MetasPromesas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='MetasUf',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ModifiedDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='PlansConservatorDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='PlansConservatorFile',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ProjectClauses',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='RealEstateLawDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='RealEstateLawFile',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ReceptionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SantanderObservations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SantanderReportDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SantanderReportFile',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SantanderState',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='StateBankObservations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='StateBankReportDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='StateBankReportFile',
            field=models.FileField(blank=True, null=True, upload_to='DocumentVentas'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='StateBankState',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='SubmissionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 18, 25, 21, 197047, tzinfo=utc)),
        ),
    ]
