# Generated by Django 4.0.2 on 2022-02-15 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('empresas_and_proyectos', '0002_remove_inmueble_maximundiscount_inmueble_blueprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='CreateAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 18, 28, 17, 793632, tzinfo=utc)),
        ),
    ]
