# Generated by Django 4.0.2 on 2022-02-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinmueble',
            name='MaximunDiscount',
        ),
        migrations.AddField(
            model_name='historicalinmueble',
            name='BluePrint',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinmueble',
            name='MaximumDiscount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='ContadoAhorroPlus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='ContadoAhorroPlusMaxDiscounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='ContadoMontoCuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='ContadoMontoEscrituraContado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='ContadoMontoPromesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='CreditoAhorroPlus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='CreditoAhorroPlusMaxDiscounts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='CreditoMontoCuotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='CreditoMontoEscrituraContado',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='CreditoMontoPromesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproyecto',
            name='DiscountMaxPercent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
